# Generated by Django 3.0.3 on 2020-02-18 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='available',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('seasonal', 'Seasonal')], default='SOME STRING', max_length=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecream',
            name='base',
            field=models.CharField(default='SOME STRING', max_length=10),
            preserve_default=False,
        ),
    ]
