# Generated by Django 3.0.3 on 2020-02-18 19:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0002_auto_20200218_1923'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='Featured_Flavor',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='icecream',
            name='date_churned',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='base',
            field=models.CharField(choices=[('chocolate', 'Chocolate'), ('vanilla', 'Vanilla')], max_length=11),
        ),
    ]
