# Generated by Django 3.0.3 on 2020-02-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0003_auto_20200218_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icecream',
            name='available',
            field=models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Seasonal', 'Seasonal')], max_length=9),
        ),
        migrations.AlterField(
            model_name='icecream',
            name='base',
            field=models.CharField(choices=[('Chocolate', 'Chocolate'), ('Vanilla', 'Vanilla')], max_length=11),
        ),
    ]
