# Generated by Django 3.0.3 on 2020-02-18 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0004_auto_20200218_2017'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icecream',
            old_name='Featured_Flavor',
            new_name='Featured',
        ),
    ]
