# Generated by Django 3.0.3 on 2020-02-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icecream', '0005_auto_20200218_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icecream',
            options={'ordering': ['flavor']},
        ),
    ]
